version: '3.4'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - './src:/app/src'

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - fudy-database:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  adminer:
    image: adminer
    depends_on:
      - database
    environment:
      - ADMINER_DEFAULT_SERVER=${DATABASE_HOST}
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  fudy-database:
